# Generated by Django 3.1.5 on 2021-01-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('ebay_price', models.FloatField()),
                ('amazon_price', models.FloatField()),
                ('ebay_tax', models.FloatField()),
                ('paypal_tax', models.FloatField()),
                ('tm_fee', models.FloatField(default=0.3)),
                ('promoted', models.FloatField(default=0.0)),
                ('profit', models.FloatField()),
            ],
        ),
    ]
