# Generated by Django 3.1.5 on 2021-01-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_saleentry_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gift_money', models.FloatField()),
                ('gift_tax', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='saleentry',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
