# Generated by Django 3.1.5 on 2021-01-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210130_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleentry',
            name='country',
            field=models.CharField(default='-----', max_length=100),
        ),
    ]
