# Generated by Django 3.1.5 on 2021-02-12 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='HipShipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_paid', models.FloatField()),
                ('seller_paid', models.FloatField()),
                ('sale_entry', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.saleentry')),
            ],
        ),
    ]
