# Generated by Django 3.1.5 on 2021-02-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210213_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnedSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_return', models.DateField()),
                ('sale', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.saleentry')),
            ],
        ),
    ]
