# Generated by Django 3.1.5 on 2021-03-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_preferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='is_paypal_edittable',
            new_name='is_paypal_editable',
        ),
    ]
