# Generated by Django 3.1.7 on 2021-04-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210327_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='default_month',
            field=models.CharField(default='lastmonth', max_length=10),
        ),
        migrations.AddField(
            model_name='preferences',
            name='start_month_day',
            field=models.IntegerField(default=16),
        ),
    ]
