# Generated by Django 3.1.7 on 2021-04-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210408_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='default_month',
            field=models.BooleanField(default=True),
        ),
    ]
