# Generated by Django 3.1.7 on 2021-04-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_preferences_sort_by_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='is_paypal_editable',
        ),
    ]
