# Generated by Django 3.1.7 on 2021-04-10 12:16

from django.db import migrations


def set_pref_month(apps, schema_editor):
    Preferences = apps.get_model('core', 'Preferences')
    for pref in Preferences.objects.all():
        pref.default_month = True
        pref.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210409_1839'),
    ]

    operations = [
        migrations.RunPython(set_pref_month),
    ]

    run_before = [
        ('core', '0018_preferences_sort_by_date'),
    ]
