# Generated by Django 3.1.7 on 2021-04-11 04:20

from django.db import migrations


def set_prefs_bool(apps, schema_editor):
    Preferences = apps.get_model('core', 'Preferences')
    for pref in Preferences.objects.all():
        if pref.is_paypal_editable == 'true':
            pref.is_paypal_editable = True
        elif pref.is_paypal_editable == 'false':
            pref.is_paypal_editable = True
        
        if pref.default_month == 'true':
            pref.default_month = True
        elif pref.default_month == 'false':
            pref.default_month = False

        if pref.sort_by_date == 'true':
            pref.sort_by_date = True
        elif pref.sort_by_date == 'false':
            pref.sort_by_date = False
        
        pref.save()
        

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_preferences_sort_by_date'),
    ]

    operations = [
        migrations.RunPython(set_prefs_bool),
    ]
