# Generated by Django 3.1.7 on 2021-04-14 10:21

from django.db import migrations, models

def set_pending_false(apps, schema_editor):
    ReturnedSale = apps.get_model('core', 'ReturnedSale')
    for sale in ReturnedSale.objects.all():
        sale.is_pending = False
        sale.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_preferences_is_paypal_editable'),
    ]

    operations = [
        migrations.RunPython(set_pending_false),
        migrations.RemoveField(
            model_name='returnedsale',
            name='date_of_return',
        ),
        migrations.AddField(
            model_name='returnedsale',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
