# Generated by Django 3.1.7 on 2021-04-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210414_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='is_constant',
            field=models.BooleanField(default=False),
        ),
    ]
