# Generated by Django 3.1.7 on 2021-04-16 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_cost_is_constant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='exp_date',
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
    ]
