# Generated by Django 3.1.7 on 2021-04-17 00:10

from django.db import migrations, models

def set_default(apps, schema_editor):
    Cost = apps.get_model('core', 'Cost')
    for cost in Cost.objects.all():
        if type(cost.is_constant) is not bool:
            cost.is_constant = True
        cost.exp_date = '9999-12-31'
        cost.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cost_exp_date'),
    ]

    operations = [
        migrations.RunPython(set_default),
        migrations.AlterField(
            model_name='cost',
            name='exp_date',
            field=models.DateField(blank=True),
        ),
    ]
