# Generated by Django 3.1.7 on 2021-04-17 00:18

from django.db import migrations


def set_default(apps, schema_editor):
    Cost = apps.get_model('core', 'Cost')
    for cost in Cost.objects.all():
        cost.is_constant = True
        cost.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210417_0310'),
    ]

    operations = [
        migrations.RunPython(set_default)
    ]
