# Generated by Django 3.1.7 on 2021-04-26 09:59

from django.db import migrations


def add_preference(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Preferences = apps.get_model('core', 'Preferences')
    for user in User.objects.all():
        if not Preferences.objects.get(user=user):
            Preferences(user=user).save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210417_0318'),
    ]

    operations = [
        migrations.RunPython(add_preference)
    ]
