# Generated by Django 3.1.7 on 2021-06-04 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210426_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
